resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: consume-data
    plan:
      - get: repo
        trigger: true

      - task: consume-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: apache/spark
              tag: "latest"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                # Install required libraries
                pip install pyspark
                # Run transformation script
                python consumption.py
                # Store output in a file
                mkdir -p output
                touch output/success.txt