resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: start-consumer
    plan:
      - get: repo
        trigger: true

      - task: start-consumer
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                pip install kafka-python
                cd repo
                python consumption.py &
                sleep 10

  - name: produce-data
    plan:
      - get: repo
        trigger: true

      - task: produce-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                pip install psycopg2
                pip install kafka-python
                cd repo
                python producer.py
