resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: produce-and-consumer-data
    plan:
      - get: repo
        trigger: true

      - task: produce-and-consume-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                pip install psycopg2-binary
                pip install kafka-python
                cd repo
                python producer.py
                # Write data to local project directory
                consumer_output.json 
