resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: produce-consume-data
    plan:
      - get: repo
        trigger: true

      - task: produce-consume-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                pip install psycopg2
                pip install kafka-python
                cd repo
                python produce_consume_data.py
                git add data.jsonl
                git commit -m "Add consumed data"
                git push origin main
