resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: run-python-script
    plan:
      - get: repo
        trigger: true

      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                echo "Installing Python libraries..."
                pip install selenium pandas sqlalchemy psycopg2-binary

                echo "Installing dependencies..."
                apt-get update && apt-get install -y wget unzip \
                  && wget -q --retry-connrefused --waitretry=2 --timeout=30 https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip \
                  && unzip -o chromedriver_linux64.zip -d /usr/local/bin/ \
                  && chmod +x /usr/local/bin/chromedriver

                echo "Verifying Chromedriver installation..."
                ls -l /usr/local/bin/chromedriver
                which chromedriver

                echo "Installing Google Chrome..."
                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
                  && dpkg -i google-chrome-stable_current_amd64.deb \
                  && apt-get -f install -y

                echo "Verifying Google Chrome installation..."
                google-chrome --version

                echo "Setting environment variables..."
                export PATH=$PATH:/usr/local/bin

                echo "Changing directory to repo..."
                cd repo

                echo "Running Python script..."
                python scrap.py

                echo "Creating output directory and file..."
                mkdir -p output
                touch output/success.txt

                echo "Script execution completed."
