resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: run-python-script
    plan:
      - get: repo
        trigger: true

      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                # Update and install system dependencies
                apt-get update && apt-get install -y wget unzip gnupg

                # Install Google Chrome
                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                dpkg -i google-chrome-stable_current_amd64.deb
                apt-get -f install -y

                # Install Chromedriver
                wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
                unzip -o chromedriver_linux64.zip -d /usr/local/bin/
                chmod +x /usr/local/bin/chromedriver

                # Verify installations
                which google-chrome
                ls -l /usr/local/bin/chromedriver
                google-chrome --version

                # Set environment variables
                export PATH=$PATH:/usr/local/bin

                # Install Python libraries
                pip install --upgrade pip selenium pandas sqlalchemy psycopg2-binary

                # Run the Python script
                cd repo
                python scrap.py

                # Store output in a file
                mkdir -p output
                touch output/success.txt
