resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/prathamesh-rs-10/vault.git
      branch: main

jobs:
  - name: run-python-script
    plan:
      - get: repo
        trigger: true

      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                echo "Updating system packages..."
                apt-get update && apt-get install -y wget unzip gnupg

                # Install required libraries for Chrome and Chromedriver
                echo "Installing required libraries..."
                apt-get install -y \
                  libnss3 \
                  libgconf-2-4 \
                  libxi6 \
                  libxrender1 \
                  libxrandr2 \
                  libxss1 \
                  libgdk-pixbuf2.0-0 \
                  libasound2 \
                  libatk1.0-0 \
                  libcups2 \
                  libdbus-1-3 \
                  libfontconfig1 \
                  libgbm1 \
                  libgtk-3-0 \
                  libpango-1.0-0 \
                  libxcomposite1 \
                  libxcursor1 \
                  libxdamage1 \
                  libxext6 \
                  libxfixes3 \
                  libxtst6 \
                  xdg-utils

                # Install Google Chrome
                echo "Installing Google Chrome..."
                wget -q "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
                dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y

                # Install Chromedriver matching the installed Chrome version
                echo "Installing Chromedriver..."
                CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
                CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*} | tr -d '\r')
                wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
                unzip -o chromedriver_linux64.zip -d /usr/local/bin/
                chmod +x /usr/local/bin/chromedriver

                # Verify Chromedriver installation
                if [ ! -x /usr/local/bin/chromedriver ]; then
                  echo "ChromeDriver installation failed"
                  exit 1
                fi

                # Verify installations
                echo "Verifying installations..."
                which google-chrome
                ls -l /usr/local/bin/chromedriver
                google-chrome --version

                # Upgrade pip and install Python libraries
                echo "Upgrading pip and installing Python libraries..."
                pip install --upgrade pip selenium pandas sqlalchemy psycopg2-binary

                # Run the Python script
                echo "Running the Python script..."
                cd repo
                python scrap.py

                # Create output directory and file
                echo "Creating output directory and file..."
                mkdir -p output
                touch output/success.txt
